### ISSUE TITLE
Changes on studio not being applied to the production

### ISSUE THREAD

**Issue by Bayramito** [sanity-io/sanity#3823] opened 2022-10-31 22:08 UTC
I have a next project and i am using sanity as CMS. Simply when i edit or add something to the project. they are not being applied to the fly. in development i can seee everything but on production not.

Is there any caching system or something? 
btw im hosting my app on the aws amplify

**Comment by geball** [comment] 2022-11-04 00:23
Closing as duplicate of #3749.

**Closed by geball** 2022-11-04 00:23 UTC
