### ISSUE TITLE
Error: Cannot find module './cors/addCorsOriginCommand'

### ISSUE THREAD

**Issue by mattlatt-at-zero** [sanity-io/sanity#1413] opened 2019-07-05 14:58 UTC
Went to upgrade Sanity and now nothing is working. I've tried completely wiping node and sanity and reinstalling. Tried clearing yarn cache. Tried manually installing cors. any ideas?

```
Unhandled rejection: Error: Cannot find module './cors/addCorsOriginCommand'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/matthew/sanity/2/node_modules/@sanity/core/lib/commands/index.js:64:52)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by rexxars** [comment] 2019-07-05 15:28
We've seen some antivirus solutions remove this file for some reason, do you have any of that running? Could you try dialing it if so?

**Comment by mattlatt-at-zero** [comment] 2019-07-05 16:20
That looks like it! Endpoint seems to think it's JS.Nemucod.6.Gen... now, how to work around that is a different story ;)

**Comment by mjansrud** [comment] 2019-07-17 12:26
I had the same problem when using npm, and tried several versions of sanity cli and core without any luck. Oddly enough, it worked fine with yarn.

**Comment by miichu** [comment] 2019-07-18 09:58
I am also experiencing this problem. Yarn install worked first time, but am not able to recreate same result afterwards. All sanity commands fails. I use Mac, so I guess they might have a default antivirus program that they run. Not sure how to switch it off to check though. Any other workarounds?

**Comment by bjoerge** [comment] 2019-07-18 14:02
It's strange that it happens on a Mac, though.

If all else fails, try removing both the `node_modules` folder and `yarn.lock` (and maybe also do a `yarn cache clean`) and then reinstall with `yarn install`?

We've had some reports in our community Slack that upgrading to latest version of yarn also helped.

**Comment by miichu** [comment] 2019-07-22 08:20
It works now! After reading the threads in the Sanity Slack community you provided, I tried checking my node version, 12.6.0, which is the latest. Apparently it is recommended to use the LTS version of node, so I downgraded to the LTS version, 10.16.0 by following these [instructions](https://apple.stackexchange.com/questions/171530/how-do-i-downgrade-node-or-install-a-specific-previous-version-using-homebrew/207883#207883?newreg=0417142996f84a3d9de48ef13fa83715). And now I can `yarn install` and use `sanity start` without problems. ✨

**Comment by mattlatt-at-zero** [comment] 2019-07-23 20:49
> It works now! The problem was my version of node, 12.6.0, which is the latest.
> 
> It was informed in the Sanity Slack that it is recommended to use the LTS version of node, so I downgraded to the LTS version, 10.16.0 by following these [instructions](https://apple.stackexchange.com/questions/171530/how-do-i-downgrade-node-or-install-a-specific-previous-version-using-homebrew/207883#207883?newreg=0417142996f84a3d9de48ef13fa83715). And now I can `yarn install` and use `sanity start` without problems. ✨

is that still working? my issue continues to be bitdefender thinking that this file is a virus...

**Comment by cristovaov** [comment] 2019-07-26 19:39
@mattlatt-at-zero @rexxars Hi there, just had the same thing happening to me right now. I also run BitDefender and this is what is said:
> Infected file detected
> 20 minutes ago
> 
> Feature:
> Antivirus
> 
> The file %USERPROFILE%/AppData\Local\Yarn\Cache\v1\npm-@sanity\core-0.141.6-2495c3dd337534d1fb94efb409bf522b09831c4f\lib\commands\cors\addCorsOriginCommand.js is infected with JS.Nemucod.6.Gen and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

JS.Nemucod.6.Gen is apparantly a ransomware/trojan but in this case seems to be a false positive.
:thinking:   
I thought it was weird because I don't use Yarn. Then looking at the CLI `package.json` I see Yarn as dev-dependency. 

I do wonder though what is the reasoning for installing Yarn (without users knowledge*) instead of doing whatever you do with the already installed package manager (in my case npm). Would there be a possibility to include a condition that '*if* yarn is installed use it *else* use npm' ?

Still though, I went and looked on their website and the [installation page for Windows](https://yarnpkg.com/en/docs/install#windows-stable) has this notice:
> Please whitelist your project folder and the Yarn cache directory (%LocalAppData%\Yarn) in your antivirus software, otherwise installing packages will be significantly slower as every single file will be scanned as it’s written to disk.

**Comment by miichu** [comment] 2019-07-31 06:55
> > It works now! The problem was my version of node, 12.6.0, which is the latest.
> > It was informed in the Sanity Slack that it is recommended to use the LTS version of node, so I downgraded to the LTS version, 10.16.0 by following these [instructions](https://apple.stackexchange.com/questions/171530/how-do-i-downgrade-node-or-install-a-specific-previous-version-using-homebrew/207883#207883?newreg=0417142996f84a3d9de48ef13fa83715). And now I can `yarn install` and use `sanity start` without problems. ✨
> 
> is that still working? my issue continues to be bitdefender thinking that this file is a virus...

It still works, although I still have to use yarn to be able to run it. 
The error occurs everytime I try to `yarn install` & `sanity start`after doing any changes to my packages, however, by doing the following instructions it works. 

1.  `rm -rf node_modules package-lock.json` 

2. `yarn cache clean` 

3. `yarn install` 

I use Mac, and my issue seemed not to lie within any antivirus solutions.

**Comment by rexxars** [comment] 2020-02-26 22:40
Not able to reproduce this, and have not heard anyone report this for a while. Closing - please comment if you encounter this issue again.

**Closed by rexxars** 2020-02-26 22:40 UTC
Labels: :bug: Bug

**Comment by y471n** [comment] 2022-12-09 00:06
I encountered this again @rexxars 
```
Error: Cannot find module 'node:path'
Require stack:
- /code/mono/sanity/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node-cjs/publicUtils.cjs
```

I'm running this inside a NextJS project with `pnpm` and Node `v14.17.6`.
