### ISSUE TITLE
Conditional fields in 3.9 scrolls the editor to the top

### ISSUE THREAD

**Issue by runesandnes** [sanity-io/sanity#4406] opened 2023-04-20 19:06 UTC
**Bug description**

When changing a field in the editor that turns on or off the visibility of a conditional field, the editor window scrolls to the top. This did not happen in 3.8.3.

**To Reproduce**

1. Define a string field with a dropdown option list.
2. Define another string field with a dropdown option list, and make the hidden property dependent on the first field
3. Whenever you change the first field to or from the blank/undefined option the editor window will scroll to the top.

**Expected behavior**

No scrolling, as was the case in 3.8.3.

**Sanity versions**

@sanity/cli (global)              3.9.0 (up to date)
@sanity/dashboard                 3.1.3 (up to date)
@sanity/eslint-config-studio      2.0.1 (up to date)
@sanity/icons                     2.3.1 (up to date)
@sanity/orderable-document-list   1.0.4 (up to date)
@sanity/production-preview       2.35.3 (up to date)
@sanity/scheduled-publishing      1.1.1 (up to date)
@sanity/table                     1.0.1 (up to date)
@sanity/vision                    3.8.3 (latest: 3.9.0)
sanity                            3.9.0 (up to date)

**Operating System**

MacOS Monterey 12.6.3

**NPM and Node version**

9.6.5
v18.14.2

**Comment by binoy14** [comment] 2023-04-26 23:08
@runesandnes could you please check if the issue is fixed in `3.9.1`

**Comment by runesandnes** [comment] 2023-05-04 17:38
Still a problem i 3.10.0 as well.
I've doble checked with a 3.8.3 branch, and there is no problem there, can't see anything else that changed at the same time.

**Comment by ifeltsweet** [comment] 2023-06-08 14:44
This happens to us on version 3.12.0 when a collapsed object field is opened and it contains at least one array field inside of it.

**Comment by xuanhung1509** [comment] 2023-07-22 04:18
I can confirm this's still present on 3.14.3

**Closed** 2023-08-01 14:09 UTC
