### ISSUE TITLE
Sanity studio default locale

### ISSUE THREAD

**Issue by FR073N** [sanity-io/sanity#4210] opened 2023-02-25 09:53 UTC
I want to have the studio interface in french.
Example : 

```
- Publish : Publier
- Delete : Supprimer
...
```

I have found localization plugins to add content languages, but what I want is something like a "defaultLocale" parameter on sanity.config.ts that would switch the default language of the app.

It may be an installable plugin and I'm willing to develop and translet it in french if you're explaining me how I can do it.

**Comment by rexxars** [comment] 2023-02-28 18:12
This is a common feature request - thanks for bumping!
Duplicate of #1603 - please give that an upvote to signal your interest :)

**Closed by rexxars** 2023-02-28 18:12 UTC
