### ISSUE TITLE
The file field does not a have browse button

### ISSUE THREAD

**Issue by olemagnus** [sanity-io/sanity#1377] opened 2019-06-19 14:25 UTC
**Is your feature request related to a problem? Please describe.**
This is no way to select a previously uploaded file in the file field in studio. 

**Describe the solution you'd like**
The file field should behave like the image field. There should be a browse button for seeing the uploaded files. 

**Describe alternatives you've considered**
Using the image field for files. It didn't work.

**Comment by JON418** [comment] 2019-09-25 19:26
+1 for this feature :)

**Comment by mskutle** [comment] 2019-09-26 13:11
+1

**Comment by igregson** [comment] 2019-10-05 00:01
Pretty surprised to see this doesn't already exist, as it's rather important for preventing lots of duplicate files being uploaded (and of course a nice and even expected UX).

**Comment by vicbergquist** [comment] 2020-07-08 10:26
Closing this as it's a duplicate of https://github.com/sanity-io/sanity/issues/1678 👍

**Comment by jdwillemse** [comment] 2020-11-17 15:11
Has anyone created a custom component for this they can share?

**Closed** 2021-08-06 09:04 UTC
Labels: :crystal_ball: Feature Request, Studio
