### ISSUE TITLE
`sanity deploy` doesn't respect user/system environment's `NODE_ENV` or `SANITY_ACTIVE_ENV`  and doesn't default to the production project & api

### ISSUE THREAD

**Issue by baybars1223** [sanity-io/sanity#3175] opened 2022-03-01 01:12 UTC
**Describe the bug**

Prior to [v2.10.5](https://github.com/sanity-io/sanity/releases/tag/v2.10.5), running `sanity deploy` would default to a production environment. I don't know if the change in v2.10.5 is actually causing the issue, or if the previous behavior just masked the issue.
Given a `sanity.json` like:
```
{
  "root": true,
  "project": {
    "name": "bar.bar.cms"
  },
  "api": {
    "projectId": "foo",
    "dataset": "production"
  },
  "plugins": [
		...
  ],
  "env": {
    "development": {
      "plugins": [
        "@sanity/vision"
      ],
      "project": {
        "name": "Bar-Dev"
      },
      "api": {
        "projectId": "baz",
        "dataset": "dev"
      }
    }
  },
  "parts": [
    {
      "name": "part:@sanity/base/schema",
      "path": "./schemas/schema"
    },
    {
      "implements": "part:@sanity/base/theme/variables/override-style",
      "path": "components/variableOverrides.css"
    },
    {
      "implements": "part:@sanity/base/brand-logo",
      "path": "components/barLogo.js"
    },
    {
      "implements": "part:@sanity/dashboard/config",
      "path": "components/dashboardConfig.js"
    },
    {
      "implements": "part:@sanity/base/document-actions/resolver",
      "path": "resolveDocumentActions.js"
    }
  ]
}
```

Previously:
`sanity start` would use `"projectId": "baz"` and `"dataset": "dev"` and 
`sanity deploy` would use `"projectId": "foo"` and `"dataset": "production"` (the project information from the root)

Now:
`sanity deploy` will not only default to `development` if _unspecified_, but will also deploy to `development` env even if `NODE_ENV` and/or `SANITY_ACTIVE_ENV` are set to `production` in the system or user's environment. I've tried adding a "production" block to the sanity.json "env" section, but it makes no difference.

Only deleting the development block from the sanity.json "env" section or creating a `.env.production` file containing fields for `SANITY_STUDIO_API_DATASET` and `SANITY_STUDIO_API_PROJECT_ID` will successfully deploy to production rather than development. This seems to contradict https://www.sanity.io/docs/sanity-json#933842c25dea and is counter-intuitive.

**Expected behavior**

The behavior of the CLI should match https://www.sanity.io/docs/sanity-json#933842c25dea or it should be made clear that the `.env.production` and `.env.development` files are no longer optional.

**Which versions of Sanity are you using?**

`2.10.5`, `2.11.0`, `2.19.0`, `2.27.0`, and more in between. The issue doesn't occur if I revert to 2.10.2 or earlier

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

node: v12.13.1
npm: 6.12.0
yarn: 1.22.17
I was primarily using yarn, but just tested with npm with the same results

**Comment by gpoole** [comment] 2022-06-15 04:04
I think this might be a duplicate of https://github.com/sanity-io/sanity/issues/2495?

**Comment by kmelve** [comment] 2023-01-13 10:08
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Closed by kmelve** 2023-01-13 10:08 UTC
Labels: bug
