### ISSUE TITLE
v3: Icons do not work in build

### ISSUE THREAD

**Issue by joaisa17** [sanity-io/sanity#3697] opened 2022-09-29 13:27 UTC
## **This is an issue with V3 studio**

**Describe the bug**

After compiling a build of studio, the following error causes the studio to crash:
```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=boolean&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at is (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:116369)
    at o (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:58067)
    at uw (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:71596)
    at i (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:120111)
    at oq (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:107174)
    at oA (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:107102)
    at oW (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:106965)
    at o5 (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:103752)
    at oF (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:102307)
    at w (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:33:1374)
```
[Decoded react error](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=boolean&args[]=)

**This error occurred to me when using icons in a schema**

**To Reproduce**

1. Create a Sanity studio in Next.js
2. Create a schema with the icon property. I used `BsAlarm` from `react-icons` as an example
3. Run `npm run build` to make a production version
4. Run `npm start` to serve the site
5. See minified React error

**Expected behavior**

An embedded studio without errors.

**Screenshots**
Expected studio:
![image](https://user-images.githubusercontent.com/89845084/193042766-47092279-16e6-40dc-ad45-4d775b3a4075.png)

Compiled studio:
![image](https://user-images.githubusercontent.com/89845084/193043102-789f195f-2a3f-4d55-8ab0-c1ee8db5aed4.png)

**Which versions of Sanity are you using?**

```
sanity 3.0.0-dev-preview.20
next 12.3.1
```

**What operating system are you using?**
`Windows 10`

**Which versions of Node.js / npm are you running?**

```
node v16.14.2
npm v8.7.0
```

**Comment by rexxars** [comment] 2022-10-20 22:23
This is indeed caused by a bug in swc - the next release of next.js will fix it. You can either disable swc with `swcMinify: false` for now, or upgrade to the canary release of next.js: [12.3.2-canary.32](https://www.npmjs.com/package/next/v/12.3.2-canary.32)

The fix will be in a proper release before/on next.js conf on Tuesday, October 25th. Leaving this open until then so others might be able to find the solution in the meantime.

**Comment by rexxars** [comment] 2022-12-12 23:16
Should now be fixed!

**Closed by rexxars** 2022-12-12 23:16 UTC
Labels: v3
