### ISSUE TITLE
Feature Request: Show current sort order and layout

### ISSUE THREAD

**Issue by Svish** [sanity-io/sanity#1626] opened 2019-11-26 15:40 UTC
**Is your feature request related to a problem? Please describe.**
There's currently no way to see which sort order is currently active. Same issue with the layout, except it's probably easier to guess from the size of the items listed (small = list, large = details)

![image](https://user-images.githubusercontent.com/142162/69648062-e3a46100-106a-11ea-8604-7eb6e421efd2.png)

**Describe the solution you'd like**
Some sort of visual indication in the list of which sort order and layout is currently active. For example a fat left primary colored border: `border-left: 3px solid ${active ? 'primary-color' : 'transparent' }`

Could also be helpful if there also was a subtle text next to the menu buttons saying something along the lines of "Sorted by Title", so you could see the current sort order without even opening the menu as well.

**Comment by Svish** [comment] 2019-11-26 15:42
Something along the lines of this?
![image](https://user-images.githubusercontent.com/142162/69648521-c623c700-106b-11ea-8ad0-37a649f7b330.png)

**Comment by vicbergquist** [comment] 2020-07-08 10:21
We have made the active sort order highlighted in an upcoming release, so I'm closing this issue 👍 Thank you for reporting!

**Comment by vicbergquist** [comment] 2020-08-18 09:55
Looks like there's a regression, so I'm reopening the issue for now 👍

**Comment by binoy14** [comment] 2024-03-19 17:59
This has been fixed in the latest version of studio.

<img width="204" alt="Screenshot 2024-03-19 at 1 58 27 PM" src="https://github.com/sanity-io/sanity/assets/6476108/41134b8a-75e9-472e-8969-bea70f0dec27">

**Closed by binoy14** 2024-03-19 17:59 UTC
Labels: enhancement, ux
