### ISSUE TITLE
Cursor jumps to start of line when writing in Korean

### ISSUE THREAD

**Issue by tony3918** [sanity-io/sanity#2090] opened 2020-10-23 13:39 UTC
**Describe the bug**
When writing within a block rich text editor in Korean, the cursor jumps to the start of the line at seemingly random intervals. Sometimes, the rich text editor even starts adding characters from right to left. This makes it very hard to write content.

**To Reproduce**
1. Create a `type: 'block'` rich text editor.
2. Start writing in Korean.
3. The cursor jumps to the start of the line while writing.

**Expected behavior**
The cursor should not jump to the start of the line while writing, just as when writing in English.

**Screenshots**
![korean-cursor-bug](https://user-images.githubusercontent.com/34783801/97010582-8d90b400-1580-11eb-8c3f-ebd523d63925.gif)

**Which versions of Sanity are you using?**
@sanity/cli             2.0.5 (up to date)
@sanity/base            2.0.7 (up to date)
@sanity/components      2.0.7 (up to date)
@sanity/core            2.0.5 (up to date)
@sanity/default-layout  2.0.7 (up to date)
@sanity/default-login   2.0.5 (up to date)
@sanity/desk-tool       2.0.8 (up to date)
@sanity/vision          2.0.5 (up to date)

**What operating system are you using?**
macOS Catalina v10.15.7

**Which versions of Node.js / npm are you running?**
npm 6.14.8
Node.js v12.18.3

**Additional context**
None

**Comment by vicbergquist** [comment] 2020-10-23 13:53
Hi and thank you for reporting! I also experienced this when writing Japanese in the editor 😔 We will look into this!

**Comment by tony3918** [comment] 2020-12-15 12:58
@vicbergquist Hello! Would it be possible to gain any hints on when this issue might be fixed? We really love your product but this issue makes it unusable for our content writers😭 Currently, we are writing our content first in google docs and then copy & paste to bypass the issue.

**Comment by DongeunPaeng** [comment] 2020-12-29 11:27
Same here! Please help.
감사합니다 🙏

**Comment by p5aholic** [comment] 2021-04-14 07:59
Is there a plan to fix this bug ?
I really love sanity, but I can‘t recommend my clients to use it because of this bug.

**Comment by d4rekanguok** [comment] 2021-09-21 09:13
Hi! This bug has been around for almost a year :( Making a text editor on the web is extremely hard so I have full empathy toward Sanity.

At first I thought this is because a korean letter is composed of smaller blocks. However, I noticed that typing Korean in bare Slate.js has no issue at all:

Portable Text (on Studio latest release, 2.20)
![Screen Recording 2021-09-21 at 5 39 53 PM](https://user-images.githubusercontent.com/3383539/134142908-4a8a92d7-77a8-4b2b-82d1-0338544bcb8a.gif)

Slate (https://www.slatejs.org/examples/richtext example, however non of the other examples have any issues with Korean text)
![Screen Recording 2021-09-21 at 5 58 32 PM](https://user-images.githubusercontent.com/3383539/134143067-191b007c-2074-4604-b3a9-108b00e350cd.gif)

...so I guess it has to do with the way portable elements are implmented on top of slate. If someone wants to take a crack at this but doesn't know Korean, here's a keyboard sequence you can use to form a 'hello' in hangul (after installing the Korean keyboard in your OS):
`d k s s u d g k t p d y`

This issue is a deal breaker for most of my clients & we can't use Sanity despite loving its features. I would love to help out in any way possible — just let me know. Thank you

**Comment by skogsmaskin** [comment] 2021-12-15 20:20
Hey! We have released a new canary where hopefully this will be fixed. I need help in confirming this, so if you are able to test it out that would be great.

Install it with:
`sanity upgrade --tag=canary --save-exact` in the root of your studio folder.

**Comment by d4rekanguok** [comment] 2021-12-16 06:43
I've just given it a try, the issue is still there but I'm glad to know this issue is actively being worked on! Thank you @skogsmaskin

**Comment by s7tya** [comment] 2021-12-18 09:06
Still there. 

Video:
https://user-images.githubusercontent.com/53410646/146635713-b8cec50c-310a-4d37-bd40-1bd651102978.mp4

**Comment by skogsmaskin** [comment] 2022-01-05 17:55
@s7tya - there is a new tagged release out where I think this is fixed. Please give it a try.

Note: new tag.

```sanity upgrade --tag=pte --save-exact```

**Comment by d4rekanguok** [comment] 2022-01-05 18:35
@skogsmaskin !! I think we're really close!

It seems to work **perfectly so far** on an empty portable text, which is awesome. However I noticed there're issues when typing underneath a custom block:

![clipped](https://user-images.githubusercontent.com/3383539/148270222-5ff14044-7891-4c9b-9151-050ab108a120.gif)

**Comment by skogsmaskin** [comment] 2022-01-05 18:51
Cool! Thanks, will check that out!

**Comment by skogsmaskin** [comment] 2022-01-05 20:08
I've released a new version.
```sanity upgrade --tag=pte --save-exact```

@d4rekanguok - I think we got it!

**Comment by d4rekanguok** [comment] 2022-01-06 03:35
@skogsmaskin I can confirm it works flawlessly so far on the latest version. This is awesome!

**Comment by skogsmaskin** [comment] 2022-01-20 15:44
Great to hear!

**Closed by skogsmaskin** 2022-01-20 15:44 UTC
Labels: :bug: Bug, :sparkles: UX, Portable Text
