### ISSUE TITLE
[v3] Desk tool preview does not work properly in build when media is undefined

### ISSUE THREAD

**Issue by joaisa17** [sanity-io/sanity#3708] opened 2022-10-03 07:31 UTC
## This is an issue with V3 Studio
**Describe the bug**

In the production version of V3 Studio, the desk tool crashes when using preview for a schema, and media is not defined.
The crash is likely the same cause for [this issue](https://github.com/sanity-io/sanity/issues/3697)

Error:
```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=boolean&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at is (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:116369)
    at o (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:58067)
    at uw (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:71596)
    at i (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:120111)
    at oq (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:107174)
    at oA (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:107102)
    at oW (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:106965)
    at o5 (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:103752)
    at oF (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:9:102307)
    at w (http://localhost:3000/_next/static/chunks/framework-99ccfeabb5d15f9f.js:33:1374)

    at ed (http://localhost:3000/_next/static/chunks/401-f7845b1ae1feb2b4.js:1431:451761)
    at ew (http://localhost:3000/_next/static/chunks/401-f7845b1ae1feb2b4.js:1431:461683)
    at Suspense
    at sk (http://localhost:3000/_next/static/chunks/401-f7845b1ae1feb2b4.js:618:1452)
    at f (http://localhost:3000/_next/static/chunks/401-f7845b1ae1feb2b4.js:1431:1023430)
    at div
    at R (http://localhost:3000/_next/static/chunks/401-f7845b1ae1feb2b4.js:1438:44626)
```
[Decoded react error](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=boolean&args[]=)

**To Reproduce**

1. Create a v3 studio environment in React (I use next.js)
2. Create a schema with preview
3. Make sure you do not use media in the preview
4. See minified react error

**Which versions of Sanity are you using?**

```
sanity 3.0.0-dev-preview.20
next 12.3.1
```

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
```
node v16.14.2
npm v8.7.0
```

**Comment by ilyagru** [comment] 2022-10-09 10:50
+1 – having the same exact issue, the related discussion https://github.com/sanity-io/sanity/discussions/3715

**Comment by jndao** [comment] 2022-10-16 18:37
+1
The issue was resolved for me by removing `swcMinify: true` from my `next.config.js`.

**Comment by rexxars** [comment] 2022-10-20 22:23
This is indeed caused by a bug in swc - the next release of next.js will fix it. You can either disable swc with `swcMinify: false` for now, or upgrade to the canary release of next.js: [12.3.2-canary.32](https://www.npmjs.com/package/next/v/12.3.2-canary.32)

The fix will be in a proper release before/on next.js conf on Tuesday, October 25th. Leaving this open until then so others might be able to find the solution in the meantime.

**Closed** 2023-01-11 19:38 UTC
Labels: bug
