### ISSUE TITLE
Hidden option on fields not working when using custom types

### ISSUE THREAD

**Issue by zambo** [sanity-io/sanity#1910] opened 2020-06-04 19:57 UTC
The `hidden` option isn't working for custom objects in the schema. 

Created this repo for reproduction: https://github.com/zambo/sanity-locale-bug-minimal-repo

Expected behaviour is to hide the language fields within the `localePageBuilder` type, the same way it does with the string and slug (and other default types).

![image](https://user-images.githubusercontent.com/497886/83803253-9ee52c80-a682-11ea-963f-aab26d6adbcc.png)

![image](https://user-images.githubusercontent.com/497886/83803383-d227bb80-a682-11ea-9101-db9ccb59c35e.png)

Sanity version: @sanity/cli version 1.149.13
OS: macOs Mojave 10.14.5
node: v12.16.3
npm: 6.14.4 

My goal here is to have a website that will have multiple language in the future, but for its launch the end user will only have access see one of the languages in the UI.

**Comment by vicbergquist** [comment] 2020-07-20 09:20
Closing as it's a duplicate of https://github.com/sanity-io/sanity/issues/1864 😊

**Closed by vicbergquist** 2020-07-20 09:20 UTC
