### ISSUE TITLE
Conditional Fields

### ISSUE THREAD

**Issue by jamesryan-dev** [sanity-io/sanity#2241] opened 2021-01-21 22:48 UTC
There isn't a problem per say but coming from a ACF / Wordpress world I was able to nest fields such that conditional logic would allow me to show/hide fields if others were selected..

Ideally to have the ability to create a schema like

Background Color or Image?
If selected one then display the correct fields for each respective choice

Thought about using the tabs plugin but thought it might confuse users about the decision and only 'one' option

Many thanks,
James

**Comment by rexxars** [comment] 2021-01-23 19:50
This is a common request, and something we want to support in the future for sure.
Duplicate of https://github.com/sanity-io/sanity/issues/677, so closing this for now

**Closed by rexxars** 2021-01-23 19:50 UTC

**Comment by vin-ni** [comment] 2022-02-01 20:44
+1
