### ISSUE TITLE
Error running sanity studio locally right after project initialization

### ISSUE THREAD

**Issue by bernardodemarco** [sanity-io/sanity#5183] opened 2023-11-14 00:52 UTC
**Describe the bug**

Unable to execute sanity studio locally right after initializing the project. The same error has also been reported [here](https://www.sanity.io/answers/typeerror-when-running--npm-run-dev--in-a-fresh-install-of-sanity-io).

**To Reproduce**

1. npm -y create sanity@latest
2. follow settings steps
3. npm run dev or sanity dev

**Expected behavior**

Default studio to be properly ran locally.

**Screenshots**
![image](https://github.com/sanity-io/sanity/assets/115510880/c812a561-d420-4292-904b-2d99368237f0)

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.19.2 (up to date)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/vision                3.19.2 (up to date)
sanity                        3.19.2 (up to date)

**What operating system are you using?**
Windows 11 with WSL2

**Which versions of Node.js / npm are you running?**

10.2.0
v21.0.0

**Additional context**

I have reproduced the same steps mentioned above in Windows and it works fine.

**Comment by bjoerge** [comment] 2023-11-14 09:49
This is caused by a bug in Node.js that's been fixed in v21.1 (see https://github.com/nodejs/node/issues/50269)

For better stability we recommend using even numbered Node versions, so v18 or v20.

**Closed** 2023-11-14 09:49 UTC
