### ISSUE TITLE
Add "Select" button for file schema type input component

### ISSUE THREAD

**Issue by alexanderflink** [sanity-io/sanity#1678] opened 2019-12-20 12:20 UTC
**Is your feature request related to a problem? Please describe.**
There is currently no way for the user of selecting a previously uploaded file when using the default input component for the "file" schema type.

**Describe the solution you'd like**
Display a "select file" button in the default input component of the "file" schema type, like the one that the "image" schema type input component has.

**Describe alternatives you've considered**
Right now this can only be solved by creating a custom input component for the "file" schema type which seems unnecessary.

**Additional context**
![image](https://user-images.githubusercontent.com/54660936/71254434-36500080-232b-11ea-8f01-3b2fcd517cd1.png)

**Comment by kmelve** [comment] 2020-01-09 05:22
This makes sense – thanks for submitting the feature request. Follow this issue for progress when we pick it up.

**Comment by vicbergquist** [comment] 2020-07-08 10:27
Closing this as it's a duplicate of https://github.com/sanity-io/sanity/issues/1377 👍

**Closed by vicbergquist** 2020-07-08 10:27 UTC
Labels: :crystal_ball: Feature Request, Studio
