### ISSUE TITLE
Error when logging in on Safari

### ISSUE THREAD

**Issue by Hooman-studio** [sanity-io/sanity#2807] opened 2021-09-27 23:44 UTC
**Describe the bug**

My client tried to login to the studio. https://**project-name**.sanity.studio/ on safari.
It got the following error message: Your browser wouldn't accept our cookie (see screenshot)

On other browsers everything is working correctly.

**Expected behavior**

Login page or going to the studio.

**Screenshots**

<img width="1911" alt="Screen Shot 2021-09-27 at 4 37 08 PM" src="https://user-images.githubusercontent.com/70230956/134999581-d102d4d2-54ca-42b3-8226-02a9b47b87b3.png">

**Comment by sarahg** [comment] 2022-01-05 00:32
I encountered this as well with Safari Version 15.2 and Sanity 2.23.1

This is probably a duplicate of https://github.com/sanity-io/sanity/issues/2198.

**Comment by rexxars** [comment] 2022-04-25 21:54
[v2.28.0](https://github.com/sanity-io/sanity/releases/tag/v2.28.0) should resolve this issue! Let us know if it does not.

**Closed by rexxars** 2022-04-25 21:54 UTC
