### ISSUE TITLE
Pasting text copied from PDF into portable text field crashes

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1452] opened 2019-08-19 13:36 UTC
**Describe the bug**
Copying text from a PDF into a portable text field crashes with this error:
![image](https://user-images.githubusercontent.com/5180175/63269519-a758ac00-c296-11e9-91d4-2a191740aa6c.png)

Copy paste to a text editor first, to convert to ASCII, makes Sanity accept the text.

**To Reproduce**
1. Copy text from [this PDF](https://mydnvglcdntqfjwwhej46g2.blob.core.windows.net/cdn/content/marketplace/docs/VAP%20terms.pdf)
2. Paste it into a portable text field in Sanity.

**Expected behavior**
Don't expect Sanity to neatly clean up the messy PDF, but would hope to get the text copied over so I could clean it up myself.

**Which versions of Sanity are you using?**
Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**
Windows.

`npm -v && node -v` outputs:
6.5.0
v11.8.0

**Comment by skogsmaskin** [comment] 2019-08-19 18:32
Thank you for the detailed report. We are going to look into it!

**Comment by george-dotdev** [comment] 2020-07-28 01:30
@bjornwang This might help: https://www.sanity.io/docs/customization#custom-paste-handling-dbbec5ed1782

**Comment by bjornwang** [comment] 2020-08-10 13:04
Thank you, @george-dotdev. We don't have a massive amount of PDFs (it was only this one), so the reason for making this issue was more to help make Sanity robust than to solve our PDF import. I'm fine with Sanity not supporting all types of formats, but the editor shouldn't crash, in my opinion, but rather give a graceful error message and possibly an attempt at pasting the content.

**Comment by skogsmaskin** [comment] 2022-01-20 15:12
I can't reproduce this any longer. Closing this issue.

**Closed by skogsmaskin** 2022-01-20 15:12 UTC
Labels: :bug: Bug
