### ISSUE TITLE
Possible to publish document that fails validation

### ISSUE THREAD

**Issue by felskov** [sanity-io/sanity#2156] opened 2020-11-27 00:06 UTC
**Describe the bug**

It seems like validation doesn't correctly pick up on required fields, for instance a slug, if they're nested inside an object. If I try to create a new instance of a document, I'm able to publish it in spite of missing one or more required fields that are nested in objects.

**To Reproduce**

1. Create a new instance of the document (use schema provided in additional context below)
2. Fill the title, but omit the slug
3. Publish button turns green
4. Clicking on publish will actually publish the document in spite of missing required fields

**Expected behavior**

I'm unable to publish a document until all validations are passing.

**Which versions of Sanity are you using?**

```bash
> sanity versions
@sanity/cli                     2.0.9 (up to date)
@sanity/base                    2.0.9 (up to date)
@sanity/block-content-to-html   1.3.8 (up to date)
@sanity/block-content-to-react  2.0.7 (up to date)
@sanity/cli                     2.0.9 (up to date)
@sanity/code-input              2.0.9 (up to date)
@sanity/components              2.0.9 (up to date)
@sanity/core                    2.0.9 (up to date)
@sanity/dashboard               2.0.9 (up to date)
@sanity/default-layout          2.0.9 (up to date)
@sanity/default-login           2.0.9 (up to date)
@sanity/desk-tool               2.0.9 (up to date)
@sanity/production-preview      2.0.5 (up to date)
@sanity/vision                  2.0.9 (up to date)
```

**What operating system are you using?**

macOS Catalina v10.15.7

**Which versions of Node.js / npm are you running?**

```bash
> npm -v && node -v
6.14.8
v14.15.1
```

**Additional context**

```js
{
  name: "test",
  type: "document",

  fields: [
    {
      name: "title",
      type: "string",
    },
    {
      type: "object",
      name: "nested",

      fields: [
        {
          name: "slug",
          type: "slug",

          options: {
            source: "title",
          },

          validation: (Rule: any) => Rule.required(),
        },
      ],
    },
  ],
},
```

**Comment by vicbergquist** [comment] 2020-11-27 07:42
Hi and thank you for reporting! 😃 This seems like a duplicate of https://github.com/sanity-io/sanity/issues/1713, so I'm closing the issue. We are aware of the problem and tracking it internally 😊

**Closed by vicbergquist** 2020-11-27 07:42 UTC
