### ISSUE TITLE
Sanity studio is permitting references to drafts

### ISSUE THREAD

**Issue by geoffreyjball** [sanity-io/sanity#2440] opened 2021-04-20 03:14 UTC
**Describe the bug**

The studio is allowing a reference to be created to a draft. When the user goes to publish that draft, it complains, as behind the scenes it cannot delete the draft document due to that strong reference.

**To Reproduce**

1. Create a draft document that can be the target of a reference in some other document. In a "typical" setup, this might be an author.
2. Go to the source of that reference (e.g., a post document), and add a reference to that draft author. Normally it wouldn't show up, but the drafts will appear.
3. Return to the draft document (in this example, the author draft) and try to publish it. You'll get a 409 Conflict error on the mutation. In the response:
`"The mutation(s) failed: Document \"drafts.41555dac-d1a5-468d-8784-f0bd8ad2d677\" cannot be deleted as there are references to it from \"ec6e2270-fd03-4e9d-b4ab-fdc9064385a5\""`

**Expected behavior**

Drafts would not be available as references, which would make the subsequent mutation error moot.

**Which versions of Sanity are you using?**

```
@sanity/cli             2.8.0 (up to date)
@sanity/base            2.8.0 (up to date)
@sanity/client          2.8.0 (up to date)
@sanity/code-input      2.2.6 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.8.0 (up to date)
@sanity/default-layout  2.8.0 (up to date)
@sanity/default-login   2.8.0 (up to date)
@sanity/desk-tool       2.8.0 (up to date)
@sanity/vision          2.8.0 (up to date)
```

**What operating system are you using?**

macOS 11.1

**Which versions of Node.js / npm are you running?**

7.6.3
v15.12.0

**Additional context**

The bug does not occur in a studio using @sanity/base 2.7.4 or earlier.

**Comment by p10e** [comment] 2021-04-20 09:35
Thanks for reporting, @geoffreyjball! This was a regression in `v2.8.0` that has now been fixed in `v2.8.1`. However, any references set to drafts under `v2.8.0` should still be manually updated to reference non-draft documents again.

For anyone running into issues doing so, e.g. if manual updates are not feasible because of the sheer number of refs, please feel free to reach out on [Slack](https://slack.sanity.io) for guidance.

**Closed by p10e** 2021-04-20 09:35 UTC

**Comment by athena9** [comment] 2021-07-12 15:49
This is happening again in 

@sanity/cli             2.12.2 (up to date)
@sanity/base            2.12.2 (up to date)
@sanity/cli             2.12.2 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.12.2 (up to date)
@sanity/dashboard       2.10.5 (up to date)
@sanity/default-layout  2.12.2 (up to date)
@sanity/default-login   2.11.1 (up to date)
@sanity/desk-tool       2.12.2 (up to date)
@sanity/vision          2.11.2 (up to date)

**Comment by summer-mute** [comment] 2023-01-24 19:00
I am running into this same issue with versions, that as far as I can tell, are the latest v2 versions.

```
Package versions:
  @sanity/cli (global)     3.2.4 (latest: 3.2.5)
  @sanity/base            2.35.4 (latest: 2.35.2)
  @sanity/core            2.35.3 (latest: 2.35.0)
  @sanity/dashboard       2.36.0 (latest: 3.1.2)
  @sanity/default-layout  2.35.4 (latest: 2.35.2)
  @sanity/default-login   2.35.4 (latest: 2.35.2)
  @sanity/desk-tool       2.35.4 (latest: 2.35.2)
  @sanity/vision          2.35.4 (latest: 3.2.5)
```

**Comment by felixmpaulus** [comment] 2025-01-21 17:01
Encountering the same error. This is super annoying since it prohibits us to from creating documents programmatically. 

I build a custom sanity tool to create documents in a bulk. Those documents reference each other. Once created, they are impossible to publish, because drafts are referencing drafts. 

To create documents in bulk, I would now have to first create and publish the parent document, and only then can I create new documents (as drafts) that reference the published root document. This is no solution, since the root document is not ready to be published yet (not ready in terms of it's content). 

<img width="715" alt="Image" src="https://github.com/user-attachments/assets/909b489b-883c-4e2e-b8d3-74128507872c" />

```
{
  "dependencies": { // not complete
    "@sanity/client": "^6.24.1",
    "@sanity/icons": "^2.11.8",
    "@sanity/image-url": "^1.1.0",
    "@sanity/overlays": "^2.3.59",
    "@sanity/portable-text-editor": "^3.48.1",
    "@sanity/preview-url-secret": "2.0.5",
    "@sanity/types": "^3.67.1",
    "@sanity/ui": "^2.10.10",
    "@sanity/vision": "^3.67.1",
    "next": "^14.2.3",
    "next-i18next": "^15.3.0",
    "next-sanity": "7.0.10",
    "next-sanity-image": "6.1.1",
  },
  "engines": {
    "node": ">=18"
  }
}
```
