### ISSUE TITLE
Editor bugs regarding Korean input

### ISSUE THREAD

**Issue by eunjae-lee** [sanity-io/sanity#1688] opened 2020-01-07 09:58 UTC
**Describe the bug**

While I tried the editor in Korean, I saw some weird behavior. I could say I saw two bugs, but not sure, so I'm just filing only one issue as "weird Korean input".

1. After typing stuff, and I hit cmd + backspace, and it crashes. The error message tells about custom component, but I wrote only plain texts in the editor.
2. Mostly at the first line, it skips a letter. Sometimes it happened after adding portable text like "Author".

Unlike English, in Korea, we need to combine pieces to form a character. I don't have enough experience in this editor things in Korean language, but I'm happy to help test if there's any potential fix.

**To Reproduce**

I tried to find exactly reproducible steps but it's not quite exact.

[Kapture 2020-01-06 at 22.25.11.mp4.zip](https://github.com/sanity-io/sanity/files/4029977/Kapture.2020-01-06.at.22.25.11.mp4.zip)

I've attached the video. It's hard to explain what's wrong and what should be right in words.
If you don't get it from the video, let me know. I'll try again to explain it.

**Which versions of Sanity are you using?**

```
➜ npx sanity versions
@sanity/cli  0.147.3 (up to date)
@sanity/cli  0.147.3 (up to date)
```

**What operating system are you using?**

macOS Catalina 10.15.2

**Which versions of Node.js / npm are you running?**

```
➜ npm -v && node -v
6.4.1
v8.16.2
```

**Comment by vicbergquist** [comment] 2020-01-17 11:41
Thanks for reporting! Closing the issue as this looks like a duplicate of https://github.com/sanity-io/sanity/issues/910.

**Closed by vicbergquist** 2020-01-17 11:41 UTC
Labels: :bug: Bug, Studio
