### ISSUE TITLE
Losing all blocktext content

### ISSUE THREAD

**Issue by snorrees** [sanity-io/sanity#1730] opened 2020-02-13 10:08 UTC
**Describe the bug**
Content Studio users are unable to undo delete operations if they delete **all** content in a block-content-field. 

This can result in users losing a lot of work, since the document history available in the Studio is not granular enough to revert the delete operation.

**To Reproduce**

In Sanity Studio:
1. Open a document with block-content field.
2. Write 'abc' in the block-content field.
4. Select all text with Ctrl+A
5. Press backspace.
6. Try to undo using Ctrl+Z
7. Undo has no effect, and the content cannot be restored. 

In some cases where another user is typing in the same block-content field while the other user deletes all content, an error message appears. 
```
/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:242 TypeError: Cannot read property 'get' of undefined
    at /static/js/app.bundle.js?cccabe0f8a33ecbd67ce:128
    at ot.__iterate (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:21)
    at ot.forEach (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:21)
    at /static/js/app.bundle.js?cccabe0f8a33ecbd67ce:128
    at ot.__iterate (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:21)
    at ot.forEach (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:21)
    at p (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:128)
    at r (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:128)
    at r (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:128)
    at onKeyDown (/static/js/app.bundle.js?cccabe0f8a33ecbd67ce:128)
```

**Expected behavior**

A user should be able to undo thier own "Select All -> Delete" operations in block-content fields.

**Which versions of Sanity are you using?**

sudo sanity versions
@sanity/cli                     1.148.1 (up to date)
@sanity/base                    1.148.2 (up to date)
@sanity/block-content-to-react    2.0.7 (up to date)
@sanity/components              1.148.1 (up to date)
@sanity/core                    1.148.1 (up to date)
@sanity/default-layout          1.148.1 (up to date)
@sanity/default-login           1.148.1 (up to date)
@sanity/desk-tool               1.148.1 (up to date)
@sanity/production-preview      1.148.1 (up to date)
@sanity/vision                  1.148.1 (up to date)

**Additional context**

Can probably be reproduced in any Sanity Studio, but these steps are based on a new Sanity studio with the "blog" template.

Chrome Version 76

**Comment by skogsmaskin** [comment] 2020-02-13 14:34
@snorrees - I think if you undo once more it will be restored. There is some unexpected behaviour related to this because when you delete everything it should be totally unset in the data, but there should still be something in the editor to type into. That's why there's an extra step here in the undo data, and we should fix this of course!

**Comment by skogsmaskin** [comment] 2020-02-18 10:32
The extra undo step is now fixed and released.

**Closed by skogsmaskin** 2020-02-18 10:32 UTC
