### ISSUE TITLE
Strange behavior when typing Japanese in block editor

### ISSUE THREAD

**Issue by p5aholic** [sanity-io/sanity#2334] opened 2021-02-26 09:23 UTC
**Describe the bug**
When typing Japanese in block editor , cursor goes to head of line sometimes.
This doesn‘t happen in normal text area. Only in block editor.

**To Reproduce**
Type Japanese in block editor

**Screenshots**
https://user-images.githubusercontent.com/15836666/109281370-91e71980-785f-11eb-9147-b46a31664fe8.mp4

**Which versions of Sanity are you using?**
```
@sanity/cli             2.0.9 (latest: 2.4.0)
@sanity/base            2.4.3 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.4.0 (up to date)
@sanity/default-layout  2.4.3 (up to date)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.4.3 (up to date)
@sanity/vision          2.2.6 (up to date)
```

**What operating system are you using?**
macOS Big Sur 11.2.2

**Which versions of Node.js / npm are you running?**
```
7.6.0
v14.15.5
```

**Comment by vicbergquist** [comment] 2021-02-26 13:04
Sorry about this! We're aware of the issue 😔 
Closing this because it's a duplicate of #2090 👍

**Closed by vicbergquist** 2021-02-26 13:04 UTC
