### ISSUE TITLE
Sorting a big list of documents doesn't work properly

### ISSUE THREAD

**Issue by dariozilocchi** [sanity-io/sanity#2651] opened 2021-08-04 17:20 UTC
**Describe the bug**

When sorting a big list of document (> 100) by a custom field, the results seems not to be correctly ordered.

1. Define the document type _post_ with the field _views_ of type number
2. Define a custom ordering for _post_, lets say: `{ field: 'views', direction: 'desc' }`
3. Import 500 _post_ records, increasing _views_ value for each one of them
4. Open the _post_ list page
5. Sort the list by _views_ by clicking on the correct option through the sorting menu
7. See that the page shows the _post_ documents with _views_ values between 100 and 1

**Expected behavior**

The page should show _post_'s documents with _views_ values between 500 and 400.

**Additional info**

Looking at the generated query through the inspector, I see:
`*[_type == $type] [0...100] | {_id, _type, views} | order(views desc) | {_id, _type}`

It seems like the slicing in the query is happening before the order, thus creating the problem.

**Which versions of Sanity are you using?**

@sanity/cli                 2.13.1 (up to date)
@sanity/base                2.13.1 (up to date)
@sanity/cli                 2.13.1 (up to date)
@sanity/color-input         2.13.0 (up to date)
@sanity/components          2.13.0 (up to date)
@sanity/core                2.13.1 (up to date)
@sanity/dashboard           2.13.1 (up to date)
@sanity/default-layout      2.13.1 (up to date)
@sanity/default-login       2.13.1 (up to date)
@sanity/desk-tool           2.13.1 (up to date)
@sanity/production-preview  2.13.0 (up to date)
@sanity/vision              2.13.1 (up to date)

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

6.14.13
v14.17.0

**Comment by cbovis** [comment] 2021-08-12 09:32
I'm also experiencing the same problem and have opened a duplicate issue. I'll close my issue down but here's the link for reference: https://github.com/sanity-io/sanity/issues/2670

**Comment by nettum** [comment] 2021-08-13 21:18
Probably same bug as #1825

**Comment by vicbergquist** [comment] 2021-08-18 09:26
Closing as it's a duplicate of #1825 👍

**Closed by vicbergquist** 2021-08-18 09:26 UTC
