### ISSUE TITLE
Content Studio: Reference Fields not working

### ISSUE THREAD

**Issue by ryanscherler** [sanity-io/sanity#709] opened 2018-04-03 18:11 UTC
Seems that a reference field (using sample 'blog' schema) doesn't properly bring up results for a given author or category. It seems to quickly flash the content below the dropdown, but is not selectable. This seems to be for all reference fields and I have tested it with Safari, Chrome and Firefox as I thought it might be a front-end bug since updating the content studio locally this morning.

**Comment by bjoerge** [comment] 2018-04-03 19:55
That's interesting. Do you see any errors in the console? Which version of sanity did you upgrade to?

**Comment by ryanscherler** [comment] 2018-04-03 20:02
Schema field JSON:

```
{
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{type: 'author'}]
},
{
      name: 'categories',
      title: 'Categories',
      type: 'array',
      of: [{type: 'reference', to: {type: 'category'}}]
},
```

**Comment by bjoerge** [comment] 2018-04-03 20:03
Thank you! That is super weird and I've never seen anything like it. I'll investigate 🔎 .

**Comment by ryanscherler** [comment] 2018-04-03 20:05
Ok thanks Bjørge!

**Comment by bjoerge** [comment] 2018-04-03 20:16
I've managed to reproduce it by creating a new project with the sample blog project. Can't see any obvious reasons to why this should stop working all of a sudden. Will have to dig deeper tomorrow.

**Comment by bjoerge** [comment] 2018-04-04 13:48
Hello again Ryan, this turned out to be a real tough bug to squash. It is caused by a regression in popper.js which we depend on through react-popper. Due to the way yarn resolves packages, it seems there's no way around it other than for us to fork react-popper, pin the version of popper.js to the one that works and release a new version of sanity that depends on this fork instead. In the meantime, if you are real stuck you could do a `sanity upgrade` (which is using yarn under the hood), then do a `rm -Rf node_modules` and then install dependencies with `npm install` instead. That should work because npm resolves packages differently than yarn.

**Comment by bjoerge** [comment] 2018-04-04 14:47
This is fixed in the latest release (update with `sanity upgrade`). Thanks a lot for your thorough issue report 🙇!

And big ups to @kristofferj for tracking down the source of this nasty 🐛

**Closed by bjoerge** 2018-04-04 14:47 UTC
Labels: bug/major, package/form-builder

**Comment by ryanscherler** [comment] 2018-04-04 16:11
Glad to help - Sounds like it was a tricky problem! I can confirm its fixed after upgrading. Thanks!

**Comment by manavm1990** [comment] 2020-11-18 16:56
I ran into this and...it turns out that I just hadn't **published** my `"reference"`
