### ISSUE TITLE
Sanity CLI does not list 'deploy' in the --help printout

### ISSUE THREAD

**Issue by jmsherry** [sanity-io/sanity#2378] opened 2021-03-12 13:40 UTC
**Describe the bug**

`--help` should list the capabilities of a package. Currently it does not list `deploy` amongst the functions

**To Reproduce**

1. In a terminal do `sanity --help`
2. Check readout for deploy and confirm its absence

**Expected behavior**
I would expect `deploy` to be listed amongst the help items

**Which versions of Sanity are you using?**
@sanity/cli  2.6.0 (up to date)

**What operating system are you using?**
Mac OSx Big Sur 11.2.1

**Which versions of Node.js / npm are you running?**
npm: 7.6.1
Node: v14.5.0

**Comment by kmelve** [comment] 2021-03-12 14:13
Thanks for reporting @jmsherry! I wonder if you run this command outside or inside a studio folder. The `sanity help` command is context-aware and will show more commands when done inside of a studio folder. Makes sense?

Will close this since it's not reproducible (within a project folder) and intended behavior.

**Closed by kmelve** 2021-03-12 14:13 UTC

**Comment by jmsherry** [comment] 2021-03-12 15:55
@kmelve Ah! Yes, that's correct! I was running sanity commands outside the folder in a terminal for things like `login`, etc. and didn't realised it would be context sensitive! 

Thank you. :)
