### ISSUE TITLE
Async prepare() in schema previews

### ISSUE THREAD

**Issue by devinhalladay** [sanity-io/sanity#2955] opened 2021-11-25 00:08 UTC
**Is your feature request related to a problem? Please describe.**
I am working on a Sanity Studio instance which has schemas for Courses and Lessons. A Course has many Lessons, so each Course has a `Lessons` field, which is an array of references to a `Lesson` document.

I then created a custom read-only input component which issues a Grok query for all documents referencing the currently open document in the Studio (shown in blue on the right):

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1934813/143326664-cba26db6-2a73-4e55-a685-e37c29c001cf.png">

The schema for that field looks like this (I cannot share the entire custom component right now):
```ts
{
      name: 'course',
      title: 'Part of Course',
      type: 'string',
      readOnly: true,
      inputComponent: ReferencedBy,
      options: {
        referenceType: 'course',
      },
    },
```

The query I am using to fetch the referencing document in my custom input (`ReferencedBy`) is:
```ts
mySanityClient
      .fetch(
        `*[_type == "${
          this.props.type.options.referenceType
        }" && references("${getPublishedId(this.props.document._id)}")]{
        ...
      }`,
```

I would like to be able to add the returned document as the `title` for previews of the `Lesson` documents. For example, when Lesson 1 (referenced by the Course "Free/Libre/Open Design" appears in Sanity Studio, I would like it to show the first referencing page's title:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1934813/143326915-c2f280b1-4031-4eb3-95ac-28b7c5173553.png">

After several attempts, I realized that `preview.prepare()` cannot be asynchronous, and is also rendered before my custom input component is rendered into the page. Therefore I cannot access the referencing document's title in time to display it as a preview field.

**Describe the solution you'd like**
I think the solution I'd like is the ability to make `preview.prepare()` in any given schema asynchronous:
```ts
{
  preview: {
    select: {
      lessonTitle: 'title',
      id: '_id',
      referencingCourse: 'course',
    },
    async prepare(selection) {
      const { lessonTitle, id, referencingCourse } = selection;

      // Query for courses which reference this lesson.
      // Here I am selecting the document's ID and passing it in the query.
      // This fetches only the first document in the array.
      const data = await client.fetch(
        `*[_type == "course" && references("${id}")] [0] { ... }`,
      );

      return {
        title: data.title,
        subtitle: lessonTitle
      };
    },
  }
}
```

That way I can fetch data within `prepare()` and render it in the preview.

**Describe alternatives you've considered**
It could also be cool to execute a grok query in `preview.select`:

```
{
  preview: {
    select: {
      lessonTitle: 'title',
      // Select the return value of a grok query
      referencingCourse: `*[_type == "course" && references("@._id")] [0] { ... }`,
    },
    prepare(selection) {
      const { lessonTitle, referencingCourse } = selection;

      return {
        // Return a value from my grok query as the title
        title: referencingCourse.title,
        subtitle: lessonTitle
      };
    },
  }
}
```

I also wondered if I could simply find a way to delay the rendering of the preview until my custom input component has rendered, but that doesn't seem possible.

And finally, I wondered whether I can get my custom input component to provide data that Sanity Studio can `select` on, but I have not found a way to do this.

**Additional context**
I think this would be a really useful feature to enable richer editing experiences! Especially for content teams who rely heavily on relations between different document types to build their content.

**Comment by devinhalladay** [comment] 2021-11-25 01:01
UPDATE: While I still think being able to execute grok queries in `preview.prepare()` would be useful, I was able to solve my particular use case by using document patches inside of my custom input component:

My input component in the document schema:
```ts
{
  name: 'course',
  title: 'Part of Course',
  type: 'string',
  readOnly: true,
  inputComponent: ReferencedBy,
  options: {
    referenceType: 'course',
  },
},
```

In `ReferencedBy.tsx`:
```tsx
const { patch } = useDocumentOperation(
  props.document._id.replace('drafts.', ''),
  'lesson',
);

useEffect(() => {
  client
    .fetch(
      `*[_type == "${
        props.type.options.referenceType
      }" && references("${getPublishedId(props.document._id)}")] [0] {
      ...
    }`,
    )
    .then((document) => {
      patch.execute([{ set: { course: document.title } }]);
    })
}, [])
``` 

And finally, back in my document schema:
```ts
preview: {
  select: {
    lessonTitle: 'title',
    course: 'course',
  },
  prepare(selection) {
    const { lessonTitle, course } = selection;

    return {
      title: course,
      subtitle: lessonTitle
    };
  },
},
```

---

Ta-daaaa!

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/1934813/143333677-da2e08cf-3da0-44df-ac49-60b0ced86f72.png">

**Comment by wimbarelds** [comment] 2022-12-16 14:11
A solution I ended up with was a custom component that calls `props.renderDefault` with modifications in `props.schemaType.preview.prepare` before and after my data has loaded.

It would be more elegant if the prepare function could return a promise instead though.

**Comment by kmelve** [comment] 2023-01-13 09:43
Thanks for reporting!

The `prepare` is not async by design to optimize performance (so that your document lists don't get stuck in a loading state). That being said, we are aware of more customization controls over document list items internally. I'll close this issue for now.

**Closed by kmelve** 2023-01-13 09:43 UTC
Labels: feature-request

**Comment by coreyward** [comment] 2023-01-14 18:14
@kmelve I'd be super curious to see how Suspense might augment/mitigate some of the challenges here. Seems like a suspense boundary could be wrapped around the list item, then a fallback synchronous preview could be rendered while waiting for an enhanced, async preview component to be ready!
