### ISSUE TITLE
Using a query/filter to get a list of references to choose from

### ISSUE THREAD

**Issue by andersnielsendk** [sanity-io/sanity#1063] opened 2018-11-26 07:36 UTC
For example when choosing which documents to highlight, you would often to only have options that are set to active/published, also that are not set to be published on a date in the future and a number of other things.

There may be other ways to structure it, to help with this issue, whether for highlight or tickets (see example in the bottom) or in any number of other cases. But as I see it, currently the data structure/schema would basically have to be build specifically to avoid issues like mentioned here, especially with big datasets, but even in smaller projects. (if using the content studio of course)

I suppose the best way would be to implement a full query (without projections?), so the options are not limited by the system:

{
title: 'highlighted_old_oscar_movies',
name: 'Highlighted old Oscar winning movies',
type: 'array',
of: [
{type: 'reference', to: {type: 'movie', query: '*[_type == "movie" && releaseYear <= 1979 && oscarsWon >= 1] | order(releaseYear, title) '}}
]
}

Or maybe like in the Structure Builder with params, filters and sort order.

In case it is simpler to implement, although it is a bit limited, an array of filters could also work. It can't handle joins, but would still solve most use cases.

{
title: 'highlighted_old_oscar_movies',
name: 'Highlighted old Oscar winning movies',
type: 'array',
of: [
{type: 'reference', to: {type: 'movie', filters: [
{'field': 'releaseYear', operator='<', value: '1979'},
{'field': 'status', operator='==', value: 'published'},
{'field': 'oscarsWon', operator='>=', value: 1}
], order: 'releaseYear, title'}}
]
}

It goes way beyond just choosing highlight items - in my specific project, I currently have to choose ticket category when creating new tickets for an event. And all ticket categories are named something like Category A, Category B etc. but have a venue reference as well as other info.
The Categories are always the same at each specific venue, so it doesn't make sense to create new ticket categories for every ticket at every event.

Without the filtering, when choosing a category on a ticket, I have ticket categories for all venues listed, which makes for a very long list, all with the same/very similar names.
I would have to change the preview in order to see which venue they belong to (And preview can't do references, so the name of the venue would also have to be in the ticket_category document) and then from that, find the correct set of tickets in a very long list.

**Comment by thomax** [comment] 2018-11-26 10:50
If I understand what your asking for, this issue is a duplicate of https://github.com/sanity-io/sanity/issues/1007. Is that correct?

A lot of developers/users are asking for a way to filter the content of a reference input. I promise you that will will provide a way to do this. I can't promise you exactly when, but you will have it :)

**Comment by andersnielsendk** [comment] 2018-11-26 10:56
At first I thought it was the same, but then I saw the request in slack, where it said:

> Is there a way to use value as key with GROQ?
> 
> Like:
> ```*[_type == 'page'] {
>   slug.current: title
> }```

So I think it's different...
But either way, I'm happy to hear that there will be a way to do this.
I understand that you can't say exactly when, but maybe you have an idea of whether it may be this year, first quarter/first half or second half of next year, or... (just to have some kind of realistic idea :-) )

**Comment by thomax** [comment] 2018-11-26 13:05
Sorry, there are so many other equally important issues (big and small) lined up these days that it would be reckless to make a promise.

That being said, developer and user feedback is gives us a very strong feel for which features are needed, so keep the issues coming 👍

**Closed by thomax** 2018-11-26 13:05 UTC
